services:
  payments:
    image: docker-registry.wikimedia.org/dev/fundraising-bookworm-php82-apache2:1.0.0

  donut:
    image: docker-registry.wikimedia.org/dev/fundraising-bookworm-php82-apache2:1.0.0

  privatebin:
    image: docker-registry.wikimedia.org/dev/fundraising-bookworm-php82-apache2:1.0.0

  email-pref-ctr:
    image: docker-registry.wikimedia.org/dev/fundraising-bookworm-php82-apache2:1.0.0

  civicrm:
    image: docker-registry.wikimedia.org/dev/fundraising-civicrm-bookworm-php82-apache2:1.0.0

  smashpig:
    image: docker-registry.wikimedia.org/dev/fundraising-bookworm-php82-apache2:1.0.0

  civiproxy:
    image: docker-registry.wikimedia.org/dev/fundraising-bookworm-php82-apache2:1.0.0

  tools:
    image: docker-registry.wikimedia.org/dev/fundraising-tools-bookworm:1.0.0

