version: '3.7'

services:
    payments:
        extends:
            file: docker-compose.yml
            service: payments
    core:
        extends:
            file: docker-compose.yml
            service: core
    donut:
        extends:
            file: docker-compose.yml
            service: donut
    privatebin:
        extends:
            file: docker-compose.yml
            service: privatebin
    email-pref-ctr:
        extends:
            file: docker-compose.yml
            service: email-pref-ctr
    civicrm:
        extends:
            file: docker-compose.yml
            service: civicrm
        volumes:
            - civi-sites:/srv/civi-sites
            - civicrm-buildkit:/srv/civicrm-buildkit/
            - civi-config:/srv/config/exposed/
            - civi-config-private:/srv/config/private/
    smashpig:
        extends:
            file: docker-compose.yml
            service: smashpig
    civiproxy:
        extends:
            file: docker-compose.yml
            service: civiproxy
    tools:
        extends:
            file: docker-compose.yml
            service: tools
    fraud-scoring:
        extends:
            file: docker-compose.yml
            service: fraud-scoring
    djangobannerstats:
        extends:
            file: docker-compose.yml
            service: djangobannerstats
    database:
        extends:
            file: docker-compose.yml
            service: database
    logger:
        extends:
            file: docker-compose.yml
            service: logger
    queues:
        extends:
            file: docker-compose.yml
            service: queues
    donorprefsqueues:
        extends:
            file: docker-compose.yml
            service: donorprefsqueues
    memcached:
        extends:
            file: docker-compose.yml
            service: memcached
    mailcatcher:
        extends:
            file: docker-compose.yml
            service: mailcatcher

volumes:
    dbdata:
    qdata:
    dpqdata:
    pbdata:
    civi-sites:
    civicrm-buildkit:
    civi-config:
    civi-config-private:

networks:
    default:
    donorprefs:
    donut: