# Setup for Fundraising development environment
# See README.md for details

version: '3.7'

# By setting an invalid default for FR_DOCKER_UID and FR_DOCKER_GID, we prevent
# bringing up the application without a user being specified (which can happen
# if setup.sh hasn't been run yet). This prevents the containers from running
# and creating files as root (which causes issues later on).
x-user:
  user: &user "${FR_DOCKER_UID:-invalid-user}:${FR_DOCKER_GID:-invalid-user}"

# This environment variable tell containers where to send logs.
# By using a variable for this, we avoid a hard dependency between images and this
# specific docker-compose setup.
x-logger:
  &logger-host FR_DOCKER_LOGGER_HOST=logger


services:
  payments:
    image: docker-registry.wikimedia.org/dev/fundraising-payments-buster-php73-apache2-xdebug:0.0.1-1
    user: *user

    ports:
      - "${FR_DOCKER_PAYMENTS_PORT:-9001}:9001"

    volumes:
      - ./src/payments/:/var/www/html/:cached
      - ./config/:/srv/config/exposed/
      - ./config-private/:/srv/config/private/

    environment:
      - *logger-host
      - COMPOSER_CACHE_DIR=/var/www/html/cache/composer

      # Provide FR_DOCKER_PAYMENTS_PORT inside the container so payments-LocalSettings.php can see it
      - FR_DOCKER_PAYMENTS_PORT=${FR_DOCKER_PAYMENTS_PORT:-9001}

      # Provide user id and group id for rsyslog to drop privileges
      - FR_DOCKER_UID
      - FR_DOCKER_GID

      # Provide the name of the service to find the right xdebug.ini files
      - FR_DOCKER_SERVICE_NAME=payments


  civicrm:
    image: docker-registry.wikimedia.org/dev/fundraising-civicrm-buster-php73-apache2-xdebug:0.0.1-1
    user: *user

    ports:
      - "${FR_DOCKER_CIVICRM_PORT:-32353}:9001"

    volumes:
      - ./src/civi-sites:/srv/civi-sites
      - ./src/civicrm-buildkit/:/srv/civicrm-buildkit/
      - ./config/:/srv/config/exposed/
      - ./config-private/:/srv/config/private/

    environment:
      - *logger-host

      # Provide user id and group id for rsyslog to drop privileges
      - FR_DOCKER_UID
      - FR_DOCKER_GID

      # Provide the name of the service to find the right xdebug.ini files
      - FR_DOCKER_SERVICE_NAME=civicrm


  database:
    image: mariadb:10.4

    ports:
      - "${FR_DOCKER_MARIADB_PORT:-3306}:3306"

    volumes:
      - dbdata:/var/lib/mysql/
      - ./config/database:/etc/mysql/conf.d

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1


  logger:
    image: docker-registry.wikimedia.org/dev/buster-rsyslog
    user: *user

    volumes:
      - ./config/:/srv/config/exposed/
      - ./logs/:/logs/


  queues:
    image: redis:5.0-buster

    volumes:
      - qdata:/data

    command: [ "redis-server", "--appendonly", "yes" ]


  memcached:
    image: memcached
    user: *user

volumes:
  dbdata:
  qdata:
