parameters:
  version: 2
  db_type: mysql_dsn
  mysql_dsn: 'mysql://root@database:3306'
  perm_type: none
  perm_user: docker
  hosts_type: none
  httpd_type: apache24
  httpd_visibility: all
  httpd_shared_ports: '32353'
  httpd_restart_command: '/usr/sbin/apache2ctl graceful'
services: {  }
