redis: &REDIS
  servers:
    scheme: tcp
    host: queues
    port: 6379
    read_write_timeout: -1

donorprefsredis: &DPREDIS
  servers:
    scheme: tcp
    host: donorprefsqueues
    port: 6379

data-store:

  mysql: &MYSQL
    class: PDO
    constructor-parameters:
      - mysql:host=database;dbname=smashpig
      - smashpig
      - dockerpass

  pending-db:
    <<: *MYSQL

  damaged-db:
    <<: *MYSQL

  fredge-db:
    class: PDO
    constructor-parameters:
      - mysql:host=database;dbname=fredge
      - drupal
      - drupal

  banner-history:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: banner-history

  contribution-tracking:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: contribution-tracking

  donations:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: donations

  jobs-adyen:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: jobs-adyen

  jobs-amazon:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: jobs-amazon

  jobs-dlocal:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: jobs-dlocal

  jobs-ingenico:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: jobs-ingenico

  jobs-paypal:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: jobs-paypal

  jobs-braintree:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: jobs-braintree

  jobs-gravy:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: jobs-gravy

  opt-in:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: opt-in

  payments-antifraud:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: payments-antifraud

  payments-init:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS

  pending:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: pending

  recurring:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: recurring

  refund:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: refund

  settle:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: settle

  unsubscribe:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: unsubscribe

  upi-donations:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *REDIS
        queue: upi-donations

  email-preferences:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *DPREDIS
        queue: email-preferences

  recurring-modify:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *DPREDIS
        queue: recurring-modify

  new-checksum-link:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *DPREDIS
        queue: new-checksum-link

  set-primary-email:
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        <<: *DPREDIS
        queue: set-primary-email

cache:
  class: SmashPig\Core\Cache\PredisCache
  constructor-parameters:
    -
      <<: *REDIS

# This is where the host directory config-private/smashpig appears in the container
# (Production equivalent comes from localsettings/local-config.)
provider-configuration-directory: /srv/config/private/smashpig

sequence-generator:
  contribution-tracking:
    class: SmashPig\Core\SequenceGenerators\PredisSequenceGenerator
    constructor-parameters:
      -
        <<: *REDIS
        sequence: contribution-tracking

mail-backend:
  smtp: true
  smtp-host: mailcatcher
  smtp-port: 1025
