data-store:
  # TODO check the FIXME below, copied from Vagrant
  # FIXME some way to reuse this between config files
  redis: &REDIS
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      -
        servers:
          scheme: tcp
          host: queues
          port: 6379

  donorprefsredis: &DPREDIS
    class: PHPQueue\Backend\Predis
    constructor-parameters:
      - servers:
          scheme: tcp
          host: donorprefsqueues
          port: 6379

  mysql: &MYSQL
    class: PDO
    constructor-parameters:
      - mysql:host=database;dbname=smashpig
      - smashpig
      - dockerpass

  pending-db:
    <<: *MYSQL

  damaged-db:
    <<: *MYSQL

  fredge-db:
    class: PDO
    constructor-parameters:
      - mysql:host=database;dbname=fredge
      - drupal
      - drupal

  banner-history:
    <<: *REDIS

  contribution-tracking:
    <<: *REDIS

  donations:
    <<: *REDIS

  jobs-adyen:
    <<: *REDIS

  jobs-amazon:
    <<: *REDIS

  jobs-dlocal:
    <<: *REDIS

  jobs-ingenico:
    <<: *REDIS

  jobs-paypal:
    <<: *REDIS

  jobs-braintree:
    <<: *REDIS

  jobs-gravy:
    <<: *REDIS

  opt-in:
    <<: *REDIS

  payments-antifraud:
    <<: *REDIS

  payments-init:
    <<: *REDIS

  pending:
    <<: *REDIS

  recurring:
    <<: *REDIS

  refund:
    <<: *REDIS

  unsubscribe:
    <<: *REDIS

  upi-donations:
    <<: *REDIS

  email-preferences:
    <<: *DPREDIS

  recurring-modify:
    <<: *DPREDIS

cache:
  class: SmashPig\Core\Cache\PredisCache
  constructor-parameters:
    -
      servers:
        scheme: tcp
        host: queues
        port: 6379

# This is where the host directory config-private/smashpig appears in the container
# (Production equivalent comes from localsettings/local-config.)
provider-configuration-directory: /srv/config/private/smashpig

sequence-generator:
  contribution-tracking:
    class: SmashPig\Core\SequenceGenerators\PredisSequenceGenerator
    constructor-parameters:
      -
        servers:
          scheme: tcp
          host: queues
          port: 6379
        sequence: contribution-tracking

mail-backend:
  smtp: true
  smtp-host: mailcatcher
  smtp-port: 1025
